/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CiudadanoData;
import AccesoADatos.Conexion;
import Entidades.Ciudadano;
import javax.swing.JOptionPane;

/**
 *
 * @author Editor
 */
public class FormularioCiudadano extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCiudadano
     */
    public FormularioCiudadano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtPatologia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtAmbitolab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        setClosable(true);

        jLabel5.setText("Patología:");

        jLabel6.setText("Ambito laboral:");

        jtPatologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPatologiaKeyTyped(evt);
            }
        });

        jLabel1.setText("Dni:");

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Correo electrónico:");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("REGISTRAR DATOS PERSONALES");

        jLabel4.setText("Teléfono:");

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoBuscar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoGuardar.png"))); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoEditar.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jbEditarInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtDni)
                    .addComponent(jtNombre)
                    .addComponent(jtCorreo)
                    .addComponent(jtTelefono)
                    .addComponent(jtPatologia)
                    .addComponent(jtAmbitolab, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jbBuscar)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAgregar)
                .addGap(39, 39, 39)
                .addComponent(jbEditar)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jbBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPatologia, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtAmbitolab, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbEditar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        CiudadanoData cd = new CiudadanoData();
        Ciudadano c1 = new Ciudadano();

        try {
            int dni = Integer.parseInt(jtDni.getText());
            c1 = cd.buscarCiudadano(dni);
            jtNombre.setText(c1.getNombre_completo());
            jtCorreo.setText(c1.getCorreo_electronico());
            jtTelefono.setText(c1.getTelefono() + "");
            jtPatologia.setText(c1.getPatologia());
            jtAmbitolab.setText(c1.getAmbito_laboral());
            jtNombre.setEditable(false);
            jtCorreo.setEditable(false);
            jtTelefono.setEditable(false);
            jtPatologia.setEditable(false);
            jtAmbitolab.setEditable(false);

        } catch (NullPointerException | NumberFormatException nf) {
            jtDni.setText("");
            JOptionPane.showMessageDialog(null, "Error al buscar, verifique los datos ingresados");
        }

    }//GEN-LAST:event_jbBuscarActionPerformed
    private void limpiarCampos() {
        jtDni.setText("");
        jtNombre.setText("");
        jtCorreo.setText("");
        jtTelefono.setText("");
        jtPatologia.setText("");
        jtAmbitolab.setText("");
    }
    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        Conexion.getConexion();
        CiudadanoData cd = new CiudadanoData();
        Ciudadano c1 = new Ciudadano();
        try {
            if (!(jtDni.getText().isEmpty() && jtNombre.getText().isEmpty()
                    && jtCorreo.getText().isEmpty() && jtTelefono.getText().isEmpty()
                    && jtAmbitolab.getText().isEmpty())) {
                c1.setDni(Integer.parseInt(jtDni.getText()));
                c1.setNombre_completo(jtNombre.getText());
                c1.setCorreo_electronico(jtCorreo.getText());
                c1.setTelefono(Long.parseLong(jtTelefono.getText()));
                c1.setPatologia(jtPatologia.getText());
                c1.setAmbito_laboral(jtAmbitolab.getText());
                cd.guardarCiudadano(c1);
               
            } else {
                JOptionPane.showMessageDialog(this, "Tenes que completar todos los campos");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Revisar los datos ingresados!!");
        } catch (NumberFormatException ex) {
            if (jtDni.getText().length() > 8) {
                JOptionPane.showMessageDialog(this, "Excediste los digitos permitidos");
            } else {
                JOptionPane.showMessageDialog(this, "Solo tenes que ingresar numeros" + ex.getMessage());
            }
        }
        limpiarCampos();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        
         jtDni.setEditable(false);
                jtNombre.setEditable(true);
                 jtCorreo.setEditable(true);
                 jtTelefono.setEditable(true);
                jtPatologia.setEditable(true);
                jtAmbitolab.setEditable(true);
         jbEditar.setText("Guardar");
         
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtPatologiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPatologiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPatologiaKeyTyped

    private void jbEditarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jbEditarInputMethodTextChanged
        try {
       
         CiudadanoData cd = new CiudadanoData();
         Ciudadano c1 = new Ciudadano();
          
               
                c1.setDni(Integer.parseInt(jtDni.getText()));
                c1.setNombre_completo(jtNombre.getText());
                c1.setCorreo_electronico(jtCorreo.getText());
                c1.setTelefono(Long.parseLong(jtTelefono.getText()));
                c1.setPatologia(jtPatologia.getText());
                c1.setAmbito_laboral(jtAmbitolab.getText());
               cd.modificarCiudadano(c1);
  
        
            }catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Revisar los datos ingresados!!");
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(this, "Solo tenes que ingresar numeros" + ex.getMessage());
        }
    }//GEN-LAST:event_jbEditarInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JTextField jtAmbitolab;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPatologia;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
