/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CentroVacunacionData;
import AccesoADatos.CiudadanoData;
import Entidades.CentroVacunacion;
import Entidades.Ciudadano;
import javax.swing.JOptionPane;

/**
 *
 * @author Editor
 */
public class FormularioCiudadano extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioCiudadano
     */
    public FormularioCiudadano() {
        initComponents();
        jtNombre.setEditable(false);
        jtCorreo.setEditable(false);
        jtTelefono.setEditable(false);
        jtPatologia.setEditable(false);
        jtAmbitolab.setEditable(false);
        jbEditar.setEnabled(false);
        jCBLocalidad.setEnabled(false);
        jCBProvincia.setEnabled(false);
        jCBProvincia.addItem("Entre Rios");
        jCBProvincia.addItem("Cordoba");
        jCBProvincia.addItem("Buenos Aires");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jtAmbitolab = new javax.swing.JTextField();
        jtDni = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtPatologia = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBProvincia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jCBLocalidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(881, 528));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("REGISTRAR DATOS PERSONALES");

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoBuscar.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jtAmbitolab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtPatologia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtPatologia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPatologiaKeyTyped(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoEditar.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbEditarMouseReleased(evt);
            }
        });
        jbEditar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jbEditarInputMethodTextChanged(evt);
            }
        });

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconoGuardar.png"))); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAgregarMouseReleased(evt);
            }
        });

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Correo electrónico:");

        jLabel5.setText("Patología:");

        jLabel6.setText("Provincia:");

        jLabel4.setText("Teléfono:");

        jLabel1.setText("Dni:");

        jLabel9.setText("Ambito laboral:");

        jCBProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Localidad:");

        jCBLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBLocalidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBLocalidadPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPatologia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscar))
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAmbitolab, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCBLocalidad, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)
                        .addComponent(jCBProvincia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jbAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbEditar)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPatologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAmbitolab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbEditar))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 440, 747));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/vacunas-1920-5.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jbEditarInputMethodTextChanged
    }//GEN-LAST:event_jbEditarInputMethodTextChanged

    private void jtPatologiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPatologiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPatologiaKeyTyped

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        CiudadanoData cd = new CiudadanoData();
        Ciudadano c1 = new Ciudadano();

        try {
            int dni = Integer.parseInt(jtDni.getText());
            c1 = cd.buscarCiudadano(dni);
            jtNombre.setText(c1.getNombre_completo());
            jtCorreo.setText(c1.getCorreo_electronico());
            jtTelefono.setText(c1.getTelefono() + "");
            jtPatologia.setText(c1.getPatologia());
            jtAmbitolab.setText(c1.getAmbito_laboral());
            
            jtNombre.setEditable(false);
            jtCorreo.setEditable(false);
            jtTelefono.setEditable(false);
            jtPatologia.setEditable(false);
            jtAmbitolab.setEditable(false);
            jCBLocalidad.setEnabled(false);
            jCBProvincia.setEnabled(false);
            jbEditar.setEnabled(true);

        } catch (NullPointerException | NumberFormatException nf) {
            jtDni.setText("");
            JOptionPane.showMessageDialog(null, "Error al buscar, verifique los datos ingresados");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEditarMouseReleased
        try {

            CiudadanoData cd = new CiudadanoData();
            Ciudadano c1 = new Ciudadano();

            c1.setDni(Integer.parseInt(jtDni.getText()));
            c1.setNombre_completo(jtNombre.getText());
            c1.setCorreo_electronico(jtCorreo.getText());
            c1.setTelefono(Long.parseLong(jtTelefono.getText()));
            c1.setPatologia(jtPatologia.getText());
            c1.setAmbito_laboral(jtAmbitolab.getText());
            System.out.println(jbEditar.getText() + " 1");
            if (jbEditar.getText().equals("Modificar")) {
                System.out.println(jbEditar.getText() + " 2");
                cd.modificarCiudadano(c1);
                jbEditar.setText("Editar");
                limpiarCampos();
                jtDni.setEditable(true);
                jtNombre.setEditable(false);
                jtCorreo.setEditable(false);
                jtTelefono.setEditable(false);
                jtPatologia.setEditable(false);
                jtAmbitolab.setEditable(false);
            } else {
                System.out.println(jbEditar.getText() + " 3");
                jtDni.setEditable(false);
                jtNombre.setEditable(true);
                jtCorreo.setEditable(true);
                jtTelefono.setEditable(true);
                jtPatologia.setEditable(true);
                jtAmbitolab.setEditable(true);
                jbEditar.setText("Modificar");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Revisar los datos ingresados!!");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Solo tenes que ingresar numeros" + ex.getMessage());
        }
    }//GEN-LAST:event_jbEditarMouseReleased

    private void jbAgregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregarMouseReleased
        jtDni.setEditable(true);
        jtNombre.setEditable(true);
        jtCorreo.setEditable(true);
        jtTelefono.setEditable(true);
        jtPatologia.setEditable(true);
        jtAmbitolab.setEditable(true);
        jbBuscar.setEnabled(false);
        CiudadanoData cd = new CiudadanoData();
        Ciudadano c1 = new Ciudadano();
        if (jbAgregar.getText().equals("Guardar")) {
            jbAgregar.setText("Nuevo");
            jtDni.setEditable(true);
            jtNombre.setEditable(false);
            jtCorreo.setEditable(false);
            jtTelefono.setEditable(false);
            jtPatologia.setEditable(false);
            jtAmbitolab.setEditable(false);
            try {
                if (!(jtDni.getText().isEmpty() && jtNombre.getText().isEmpty()
                        && jtCorreo.getText().isEmpty() && jtTelefono.getText().isEmpty()
                        && jtAmbitolab.getText().isEmpty())) {
                    c1.setDni(Integer.parseInt(jtDni.getText()));
                    c1.setNombre_completo(jtNombre.getText());
                    c1.setCorreo_electronico(jtCorreo.getText());
                    c1.setTelefono(Long.parseLong(jtTelefono.getText()));
                    c1.setPatologia(jtPatologia.getText());
                    c1.setAmbito_laboral(jtAmbitolab.getText());
                    cd.guardarCiudadano(c1);
                    jbAgregar.setText("Nuevo");
                    jbBuscar.setEnabled(true);
                    jtDni.setEditable(true);
                    jtNombre.setEditable(false);
                    jtCorreo.setEditable(false);
                    jtTelefono.setEditable(false);
                    jtPatologia.setEditable(false);
                    jtAmbitolab.setEditable(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Tenes que completar todos los campos");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Revisar los datos ingresados!!");
            } catch (NumberFormatException ex) {
                if (jtDni.getText().length() > 8) {
                    JOptionPane.showMessageDialog(this, "Excediste los digitos permitidos");
                } else {
                    JOptionPane.showMessageDialog(this, "Solo tenes que ingresar numeros" + ex.getMessage());
                }
            }

        } else {
            jbAgregar.setText("Guardar");
        }
        limpiarCampos();
    }//GEN-LAST:event_jbAgregarMouseReleased

    private void jCBLocalidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBLocalidadPopupMenuWillBecomeVisible
        
    }//GEN-LAST:event_jCBLocalidadPopupMenuWillBecomeVisible
    
  
    
    private void limpiarCampos() {
        jtDni.setText("");
        jtNombre.setText("");
        jtCorreo.setText("");
        jtTelefono.setText("");
        jtPatologia.setText("");
        jtAmbitolab.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCBLocalidad;
    private javax.swing.JComboBox<String> jCBProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JTextField jtAmbitolab;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPatologia;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
